from __future__ import annotations

from typing import Protocol


class CommonRepository(Protocol):
    def fetch_active_members(self): ...
    def fetch_document_link_options(self): ...
    def fetch_task_link_options(self): ...
    def fetch_parent_task_options(self, exclude_task_id: int | None = None): ...


class DocumentsRepository(Protocol):
    def fetch_document_folders(self, doc_type: str | None = None): ...
    def fetch_folder(self, folder_id: int): ...
    def ensure_folder(self, doc_type: str, folder_name: str): ...
    def fetch_document_with_relations(self, document_id: int): ...
    def list_documents(
        self, *, search: str, doc_type: str, tag: str, folder_id: str, limit: int, offset: int
    ): ...
    def fetch_tag_options(self): ...
    def create_document(self, data, folder_id): ...
    def create_document_asset(
        self,
        *,
        document_id: int | None,
        draft_key: str | None,
        object_key: str,
        url: str,
        original_filename: str,
        content_type: str,
        size: int,
    ): ...
    def fetch_document_assets(self, document_id: int): ...
    def fetch_document_asset(self, asset_id: int): ...
    def delete_document_asset(self, asset_id: int): ...
    def assign_draft_assets(self, document_id: int, draft_key: str): ...
    def sync_document_tags(self, document_id: int, tags_text: str): ...
    def sync_task_documents(self, document_id: int, task_ids: list[int]): ...
    def update_document(self, document_id, data, folder_id): ...
    def delete_document(self, document_id): ...
    def update_document_folder(self, document_id, doc_type, folder_id): ...


class WbsRepository(Protocol):
    def fetch_task_with_links(self, task_id: int): ...
    def fetch_tasks_for_filters(self, filters: dict[str, str]): ...
    def create_task(self, data): ...
    def sync_task_documents(self, task_id: int, document_ids: list[int]): ...
    def update_task(self, task_id: int, data): ...
    def delete_task(self, task_id: int): ...


class MembersRepository(Protocol):
    def fetch_member(self, member_id: int): ...
    def list_members(self): ...
    def create_member(self, data): ...
    def update_member(self, member_id: int, data): ...
    def delete_member(self, member_id: int): ...


class SchedulesRepository(Protocol):
    def fetch_schedule(self, schedule_id: int): ...
    def list_schedules(self): ...
    def create_schedule(self, data): ...
    def update_schedule(self, schedule_id: int, data): ...
    def delete_schedule(self, schedule_id: int): ...


class DashboardRepository(Protocol):
    def fetch_dashboard_summary(self, today_str: str): ...
    def fetch_week_due_tasks(self, today_str: str, week_end_str: str): ...
    def fetch_recent_documents(self): ...
    def fetch_recent_tasks(self): ...
    def fetch_pinned_notice(self): ...
    def fetch_upcoming_schedules(self, today_str: str): ...
